### ISSUE TITLE
config.js file not used

### ISSUE THREAD

**Issue by binerf** [xwiki-labs/cryptpad-docker#12]
**Describe the bug**
After creating my account into fresh install of Cryptpad, I copied my key and pasted it into `config.js` (based on `config.example.js`).
`config.js` located in `/mnt/docker/cryptpad/customize` (see below).

When I try to reach https://cryptad.mydomain/admin, I get "Seuls les administrateurs ont accès à cette page" (own translation: "Only admin have access to this page")

**Environment**
- own nginx reverse proxy
- Ubuntu server
- docker
```
docker run -i -t -d \
        -v /mnt/docker/cryptpad/data/blob:/cryptpad/blob \
        -v /mnt/docker/cryptpad/data/block:/cryptpad/block \
        -v /mnt/docker/cryptpad/data/data:/cryptpad/data \
        -v /mnt/docker/cryptpad/data/files:/cryptpad/datastore \
        -v /mnt/docker/cryptpad/customize:/cryptpad/customize \
        -p 127.0.0.1:3000:3000 \
        -p 127.0.0.1:3001:3001 \
        --restart unless-stopped \
        --name=cryptpad \
        promasu/cryptpad
```

**Used app version**
- Docker promasu/cryptpad

**Comment by Asharas** [comment]
As per [CryptPad's installation guide](https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide#configuration) the config is read from the `$cryptpath/config` directory, in that case `/cryptpad/config`.  

Your config should be mounted with `-v /mnt/docker/cryptpad/config:/cryptpad/config`.  
Note that directly mounting the file instead of the directory containing it works too.

**Comment by binerf** [comment]
Hi,

Thanks for your feedback.
Indeed,this solution works! Thanks.

Still don't understand how I missed this documentation...

Anyway, many thanks!
