### ISSUE TITLE
[nginx-alpine] don't set HSTS header

### ISSUE THREAD

**Issue by Loader009** [xwiki-labs/cryptpad-docker#38]
HSTS should be set as an option, not hardcoded.
You're breaking my HSTS preload with this.

**Comment by almereyda** [comment]
Following the latest available documentation for this repository in https://github.com/xwiki-labs/cryptpad-docker/blob/72dd7030c1dc1c70b5ff3f53b8451f5af19a2927/README.md#general-notices, the section 'General notices' begins with an 'Important' point about this image having switched to an integrated `nginx` for correctly setting Content-Security-Policy headers.

While it could also be achieved with other forms of web routing, e.g. through Caddy #13 or the often externally referred Traefik, this has yet to be exemplified.

The section 'Standalone install' below gives advice on how to install manually by using the Docker images provided without `nginx`, with also linking to

- https://github.com/xwiki-labs/cryptpad/wiki/Installation-guide#opening-cryptpad-to-the-internet
  - https://docs.cryptpad.fr/en/admin_guide/installation.html#install-and-configure-nginx
    - https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf

for an example configuration that uses `nginx` for the desired purposes. The same as above applies here, that one would have to configure another system similarly, in order to achieve the same results: there is an option for you available to configure HSTS headers by yourself, but you would have to walk the long path to double check your local modifications against the available upstream specifications.
